
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  user_id INT,
  amount NUMERIC,
  status TEXT
);

ALTER TABLE users  REPLICA IDENTITY FULL;
ALTER TABLE orders REPLICA IDENTITY FULL;
